export enum EventActivityAction {
  CREATED = 'CREATED',
  SUBMITTED = 'SUBMITTED',
  REJECTED = 'REJECTED',
  APPROVED = 'APPROVED',
  RESUBMITTED = 'RESUBMITTED',
  CHANGES_SUBMITTED = 'CHANGES_SUBMITTED',
  CHANGES_APPROVED = 'CHANGES_APPROVED',
  CHANGES_REJECTED = 'CHANGES_REJECTED',
}
